
package org.javahd.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CoursesIntf", targetNamespace = "http://service.javahd.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CoursesIntf {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addCourse", targetNamespace = "http://service.javahd.org/", className = "org.javahd.service.AddCourse")
    @ResponseWrapper(localName = "addCourseResponse", targetNamespace = "http://service.javahd.org/", className = "org.javahd.service.AddCourseResponse")
    @Action(input = "http://service.javahd.org/CoursesIntf/addCourseRequest", output = "http://service.javahd.org/CoursesIntf/addCourseResponse")
    public boolean addCourse(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

    /**
     * 
     * @return
     *     returns java.util.List<org.javahd.service.Courses>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "showCourses", targetNamespace = "http://service.javahd.org/", className = "org.javahd.service.ShowCourses")
    @ResponseWrapper(localName = "showCoursesResponse", targetNamespace = "http://service.javahd.org/", className = "org.javahd.service.ShowCoursesResponse")
    @Action(input = "http://service.javahd.org/CoursesIntf/showCoursesRequest", output = "http://service.javahd.org/CoursesIntf/showCoursesResponse")
    public List<Courses> showCourses();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteCourse", targetNamespace = "http://service.javahd.org/", className = "org.javahd.service.DeleteCourse")
    @ResponseWrapper(localName = "deleteCourseResponse", targetNamespace = "http://service.javahd.org/", className = "org.javahd.service.DeleteCourseResponse")
    @Action(input = "http://service.javahd.org/CoursesIntf/deleteCourseRequest", output = "http://service.javahd.org/CoursesIntf/deleteCourseResponse")
    public boolean deleteCourse(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
